# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u31zIzsX8fqmxM75X7uNDCPJE6W1vi4i
"""

#!/usr/bin/env python3
# corpus_manager.py
# Utility script for managing the Weihnachtsansprachen corpus

import os
import re
import csv
from pathlib import Path
from collections import Counter

CORPUS_ROOT = Path(__file__).resolve().parent.parent
SPEECHES_DIR = CORPUS_ROOT / 'speeches'
METADATA_PATH = CORPUS_ROOT / 'CORPUS_METADATA.csv'


def load_text(filepath):
    with open(filepath, encoding='utf-8') as f:
        return f.read()


def simple_tokenize(text):
    return re.findall(r'\b[\wäöüÄÖÜß]+\b', text.lower())


def ttr(tokens):
    if not tokens:
        return 0.0
    return len(set(tokens)) / len(tokens)


def speech_stats(filepath):
    text = load_text(filepath)
    tokens = simple_tokenize(text)
    return {
        'tokens': len(tokens),
        'types': len(set(tokens)),
        'ttr': round(ttr(tokens), 4),
        'chars': len(text)
    }


def corpus_overview(speeches_dir=SPEECHES_DIR):
    rows = []
    for speaker_dir in sorted(speeches_dir.iterdir()):
        if not speaker_dir.is_dir():
            continue
        for txt_file in sorted(speaker_dir.glob('*.txt')):
            stats = speech_stats(txt_file)
            rows.append({
                'speaker': speaker_dir.name,
                'file': txt_file.name,
                **stats
            })
    return rows


def top_words(filepath, n=20, stopwords=None):
    tokens = simple_tokenize(load_text(filepath))
    if stopwords:
        tokens = [t for t in tokens if t not in stopwords]
    return Counter(tokens).most_common(n)


def load_metadata(metadata_path=METADATA_PATH):
    with open(metadata_path, encoding='utf-8') as f:
        return list(csv.DictReader(f))


if __name__ == '__main__':
    rows = corpus_overview()
    print(f'Corpus: {len(rows)} speeches')
    for r in rows:
        print(r)
